version: "3.7"

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_user_pass
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user_pass
      
  my-app:
    image: kayretli/bookstore:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
